import streamlit as st
from utils.state import define_session_states

# create session state variables
define_session_states()

st.image("assets/image.png")
st.header("Hackermen")

st.markdown("Use this page for a more detailed analysis of data that is generated by the Home Page.")

if st.session_state["df"] is None or st.session_state["figure"] is None:
    st.warning("**Make sure to generate your data first before proceeding with the analysis!**")
else:
    st.subheader("Raw Data")
    st.markdown("These are the raw data that are obtained from the API calls.")
    st.dataframe(st.session_state["df"])

    st.subheader("Plots")
    st.markdown("To better visualise the data, let's take a look at key variables used for our analysis. "
                "We used 5 main variables to analyse the current weather conditions of the route to let us "
                "better plan out the **safest** and **sustainable** route ships can take between "
                "PSA's ports.")
    st.markdown("The following exerpt explains the reasons why we have decided to use the 5 variables for determining the best ship routes:\n"
                "* **Sea Surface Temperature**: This is useful for helping us to determine cooler regions where extreme weather conditions are "
                "not likely to occur (warmer seas > greater likelihood of extreme weather conditions [cyclones, hurricanes] > greater threat to ship safety)\n"
                "* **Sea Current Speed**: Determines the calmness of the sea, the lower the speeds, the more calm the seas are, and the greater the safety of travel\n"
                "* **Significiant Wave Heights**: Allows us to determine the overall safety and viability of ship routes, since greater waves allow us to generate"
                "more tidal energy, but too large of a wave might pose a danger to the ship\n"
                "* **Tides**: Similar to Significant Wave Heights, to allow us to determine overall viability of travel due to generation of tidal energy on ships\n"
                "* **Surge**: Surges are the temporary rise on sea level, caused by weather conditions. This helps us to assess the overall safety of ships along "
                "planned routes")
    st.pyplot(st.session_state["figure"])
